### ISSUE TITLE
Som en admin vill jag kunna se användarrecensioner på produkter

### ISSUE THREAD

**Issue by SebastianWirstrom** [Rika-group-7/Rika-AdminPortal-Webapp#54]
![new-reviews](https://github.com/user-attachments/assets/6db82c83-3240-46c7-8e1c-d13f2c44cdce)

### Description

As an admin user, it should be possible to reply to view user reviews on products. There should be a page in the backoffice app where all reviews are gathered, and where the admin can filter and sort reviews from criteria such as reviewer profile, review score, product id, etc. Upon visiting the page, new (pending) reviews should be shown first.
Clicking a review item should take the admin to a detailed view of the review. From the list it should also be possible to navigate to products and user profiles.

### Tasks

- [ ] Create page for listing user reviews
- [ ] Implement filter and sorting functionality
- [ ] Create user review data entity
- [ ] Create backend logic for handling user reviews
- [ ] Link user review data entity to product data entity

### Acceptance criteria

- [ ] User review items are correctly listed
- [ ] Pending user reviews are prioritized
- [ ] Filtering only shows items according to filter criteria
- [ ] Sorting shows items according to sort criteria
- [ ] Navigating to a detailed view works correctly
- [ ] Navigating to a user profile works correctly
- [ ] Navigating to a product view works correctly

### Test cases

- User review items are correctly listed
- Pending user reviews are prioritized
- Filtering only shows items according to filter criteria
- Sorting shows items according to sort criteria
- Navigating to a detailed view works correctly
- Navigating to a user profile works correctly
- Navigating to a product view works correctly
