### ISSUE TITLE
Som en admin vill jag kunna moderera användarrecensioner på produkter

### ISSUE THREAD

**Issue by SebastianWirstrom** [Rika-group-7/Rika-AdminPortal-Webapp#55]
![manage-user-review](https://github.com/user-attachments/assets/eacc30ea-1e30-4c58-9b6e-e0fbbb3fef42)

### Description

As an admin user, it should be possible to manage a user review. When viewing review details, the admin can change status of the review (published, unpublished, pending, removed). The admin should also be able to leave a reply to the review, which will be published to the product review on the webshop page. The admin should not be able to edit the data submitted by the reviewer in any way (i.e. editing comment, changing review score, etc.).
The admin should also be able to navigate to the user profile or see the users other submitted reviews from the details view. The admin should also be able to block or unblock (if previously blocked) a user from leaving future reviews. When a review changes status and/or if a user's reviewing privileges are changed, the user should be notified via an email.
When saving a reply and/or changing review status, the corresponding database entries should be updated.

### Tasks

- [ ] Create backoffice page for viewing a user review
- [ ] Create form for managing user review
- [ ] Implement user review service
- [ ] Create data entity for blocked user
- [ ] Link blocked user entity to user account entity
- [ ] Link to user account's user reviews

### Acceptance criteria

- [ ] All review details data should be displayed correctly
- [ ] Sending admin reply saves the reply to the database
- [ ] Changing review status updates the review entry in the database
- [ ] Email is sent to user when review status changes in database
- [ ] Email is sent to user when admin reply is saved to database
- [ ] On saving changes to the review, the page is updated with newly retrieved data from the database
- [ ] Navigating to user profile functions
- [ ] Navigating to user reviews functions

### Test cases

- All data is correctly displayed
- Reply is saved to database
- Status change is updated in database
- Reply email is sent to user
- Status change email is sent to user
- Page is updated correctly when saving new data
