### ISSUE TITLE
Som en admin vill jag kunna lämna kommentarer på användarrecensioner

### ISSUE THREAD

**Issue by SebastianWirstrom** [Rika-group-7/Rika-AdminPortal-Webapp#56]
### Description

As an admin user, it n should be able to leave a reply on a product review, which will be published to the product review on the webshop page. When leaving a reply, the customer who submitted the review should be notified via email, and the reply should be saved to the database.

### Tasks

- [ ] Create text editor on user review details page in backoffice
- [ ] Create data entity for admin reply
- [ ] Link admin reply data entity to user review data entity

### Acceptance criteria

- [ ] Sending admin reply saves the reply to the database
- [ ] Email is sent to user when admin reply is saved to database

### Test cases

- Reply is saved to database
- Reply email is sent to user
- Page is updated correctly when saving new data
