### ISSUE TITLE
Som en admin vill jag kunna se öppna supportärenden (inkomna via e-post)

### ISSUE THREAD

**Issue by SebastianWirstrom** [Rika-group-7/Rika-AdminPortal-Webapp#57]
![open-support-tickets](https://github.com/user-attachments/assets/e46459c9-d02b-4d5e-bb2e-f1473c54e479)

### Description

Implement functionality in backoffice app that allows a logged in admin user to see support tickets sent via email or as text messages from the webshop app. Open (unhandled) tickets should be prioritized and listed immediately when the admin user navigates to the page. From the same page, it should be possible to also list all tickets regardless of status. It should be possible to filter or sort support tickets on different criteria such as submit date, status, client name etc.

### Tasks

- [ ] Create backoffice support page
- [ ] Create list/table of support tickets
- [ ] Implement filter and sort functionality for support tickets
- [ ] Set up support email service
- [ ] Create data entities for support tickets

### Acceptance criteria

- [ ] Open tickets should be shown first
- [ ] If a filter is active, only tickets meeting the filter criteria should be shown
- [ ] Filter and sorting should not require reloading the page
- [ ] Clicking a support ticket should take the user to ticket details
- [ ] The user should be notified when a new support ticket has been submitted, regardless of the current filter/sort view

### Test cases

- Test that open tickets are prioritized
- Test filter
- Test sorting
- Test async update of page data on filter/sort
- Test navigating to ticket details
- Test notification of new support tickets
