### ISSUE TITLE
Som en admin vill jag kunna se öppna supportärenden (inkomna via chat-requests)

### ISSUE THREAD

**Issue by SebastianWirstrom** [Rika-group-7/Rika-AdminPortal-Webapp#58]
![open-support-tickets](https://github.com/user-attachments/assets/4f497e20-f04e-4c32-85c1-09a7b5d9f56d)

### Description

Implement functionality in backoffice app that allows a logged in admin user to see support chat requests submitted by a user from the webshop app. Open (unhandled) requests should be prioritized and listed immediately when the admin user navigates to the page. From the same page, it should be possible to also list previous chat logs the admin user has participated in. It should be possible to filter and sort chat logs based on criteria such as client user name, date saved, etc.

### Tasks

- [ ] Create backoffice support page
- [ ] Implement filter and sort functionality for support tickets
- [ ] Set up support chat service
- [ ] Set up logging for support chat

### Acceptance criteria

- [ ] Open chat requests should be shown first
- [ ] If a filter is active, only chat logs meeting the filter criteria should be shown
- [ ] Filter and sorting should not require reloading the page
- [ ] Clicking a support chat request should take the user to a chatroom with the client
- [ ] Clicking a chat log item should take the user to the chat log
- [ ] The user should be notified when a new support chat request has been submitted, regardless of the current filter/sort view

### Test cases

- Test that open requests are prioritized
- Test filter
- Test sorting
- Test async update of page data on filter/sort
- Test navigating to chat room
- Test navigating to chat log details
- Test notification of new support chat request
