### ISSUE TITLE
Som en admin vill jag kunna svara på öppna supportärenden genom att skicka e-post

### ISSUE THREAD

**Issue by SebastianWirstrom** [Rika-group-7/Rika-AdminPortal-Webapp#59]
![support-message](https://github.com/user-attachments/assets/c90ee16d-4006-4bb8-8cfb-48255335f858)
![support-message-2](https://github.com/user-attachments/assets/a50032a1-742b-4b78-8f17-821cc7c71529)

### Description

As an admin user, it should be possible to reply to a support ticket send via email or as a support message from the webshop app. Viewing the support message should show all relevant information, including sender, sender profile (if exists), message, current status, etc. The admin should be able to write a reply using a text editor on the page view. Submitting the reply should send an email containing the reply as well as all other relevant support ticket information to the client that submitted the support message.
The admin should also be able to change status of the support ticket, When status of a support ticket is changed, an email should be sent to the client that submitted the support message to notify them of the change.

### Tasks

- [ ] Create page for viewing a support message
- [ ] Create text editor for writing an email
- [ ] Link to user profile on backoffice webapp
- [ ] Implement support message service

### Acceptance criteria

- [ ] All support message details are correctly displayed
- [ ] The admin can successfully write and send a reply
- [ ] When a reply is send, it is saved to the database
- [ ] When a reply is saved in the database, an email is sent to the client (containing reply and ticket information)
- [ ] When support ticket status is changed, corresponding database entry is updated
- [ ] When ticket status entry is changed in database, an email is send to the client informing them of status change
- [ ] On saving changes to the ticket (ie sending reply and/or changing status), the web page is updated with new retrieved data from database

### Test cases

- Message information is correctly displayed
- Reply is saved to database
- Reply email is sent to client
- Ticket status is saved to database
- Status change message is sent to client
- Page is correctly updated when saving new data
