### ISSUE TITLE
Som en admin vill jag kunna hämta ut rapporter baserat på befintlig användardata så att jag kan analysera om användarnas aktivitet och användning av tjänsten.

### ISSUE THREAD

**Issue by SebastianWirstrom** [Rika-group-7/Rika-AdminPortal-Webapp#62]
**Aktivitets Diagram:**
![image](https://github.com/user-attachments/assets/68ea4d39-57cc-4c0b-8d24-a16757fb45cb)
**Sekvens Diagram:**
![image](https://github.com/user-attachments/assets/59330559-fc85-4848-978e-0d195cedfc22)

**Task:**
- [ ] Skapa en knapp på admin sidan för att generera rapporter.
- [ ] Implementera ett formulär där admin kan välja filtrerings alternativ så som tidsperiod, användargrupp eller aktivitetsnivå.
- [ ] Skicka förfrågan till backend för att generera en rapport baserad på de valda filtrerings alternativen.
- [ ] Hämta rapporten i önskat format så som PDF eller Excel och ladda ner.
- [ ] Visa bekräftelsemeddelande om rapporten genererades eller visa ett felmeddelande om det uppstod problem.

**Acceptanskriterier:**
- [ ] Knapp för rapport generering: Knappen för att generera rapporter ska vara synlig på admin sidan.
- [ ] Filtrerings alternativ: Admin ska kunna välja filter för att generera anpassade rapporter.
- [ ] Rapportformat: Rapporten ska kunna laddas ner i önskat format, t.ex. PDF eller Excel.
- [ ] Bekräftelsemeddelande: Admin ska få en bekräftelse när rapporten har genererats, eller ett felmeddelande om det inte gick att generera rapporten.
