### ISSUE TITLE
Som en admin vill jag kunna hämta ut rapporter på lagerstatus för att kunna följa upp lagersaldo inför inventering.

### ISSUE THREAD

**Issue by SebastianWirstrom** [Rika-group-7/Rika-AdminPortal-Webapp#64]
**Aktivitets Diagram:**
![image](https://github.com/user-attachments/assets/75348527-7f9a-4650-854f-87156585c6c7)
**Sekvens Diagram:**
![image](https://github.com/user-attachments/assets/151e3e37-3825-47fb-a264-828381c14044)

**Task:**
- [ ] Skapa en knapp på rapport sidan för att generera lagerstatusrapport.
- [ ] Implementera ett formulär där admin kan välja filtreringsalternativ (t.ex. produktkategori, lagernivå, lagerplats).
- [ ] Skicka en förfrågan till backend för att generera lagerstatus rapport baserat på de valda filtrerings alternativen.
- [ ] Hämta lagerstatus rapport i önskat format (t.ex. PDF eller Excel) och ladda ner den till admins dator.
- [ ] Visa ett bekräftelsemeddelande om rapporten genererades framgångsrikt eller visa ett felmeddelande om det uppstod problem.

**Acceptanskriterier:**
- [ ] Knapp för lagerstatus rapport: Knappen för att generera lagerstatusrapporten ska vara synlig på rapport sidan.
- [ ] Filtrerings alternativ: Admin ska kunna välja filter för att generera en anpassad lagerstatus rapport.
- [ ] Rapportformat: Lagerstatus rapport ska kunna laddas ner i önskat format, t.ex. PDF eller Excel.
- [ ] Bekräftelsemeddelande: Admin ska få en bekräftelse när lagerstatus rapport har genererats, eller ett felmeddelande om det inte gick att generera rapporten.
