### ISSUE TITLE
Som en admin vill jag kunna navigera till en användarsida som listar upp alla användare för att kunna söka och hitta befintliga användare.

### ISSUE THREAD

**Issue by HugoSpangberg** [Rika-group-7/Rika-AdminPortal-Webapp#68]
![image](https://github.com/user-attachments/assets/965cad8c-1969-4d92-a070-9419b0a64980)

**Task:**
- [ ] Implementera en knapp i adminpanelen som navigerar till användarsidan.
- [x] Skapa en sida som hämtar och visar alla användare från databasen, inklusive deras namn, efternamn och e-post.
- [x] Skapa en sökfunktion för enklare navigering till specifik användare.

**Acceptanskriterier:**
- [ ] När en admin klickar på knappen i adminpanelen, ska de navigeras till en sida som listar alla användare.
- [x] Alla användare i databasen ska visas på användarsidan.
- [x] Varje användare ska visas med relevant information som namn och e-postadress.
- [x] Sidan ska ladda användarlistan inom rimlig tid.

**Testkriterier:**
- [ ] Säkerställ att alla användare i databasen visas korrekt på användarsidan.
**Förväntat resultat:** Varje användare visas med namn och e-post.
- [ ] Säkerställ att sökfunktionen funkar på sidan.
**Förväntat resultat:** Användaren man sökt på ska visas.
