### ISSUE TITLE
Som en admin vill jag kunna navigera in på en användare profil sida som visar användarens köphistorik, e-postadress och adress information.

### ISSUE THREAD

**Issue by HugoSpangberg** [Rika-group-7/Rika-AdminPortal-Webapp#69]
**Aktivitets Diagram**
![image](https://github.com/user-attachments/assets/e9a2beeb-8fbe-4b6d-b030-9eba8b665731)

**Sekvens Diagram:**
![image](https://github.com/user-attachments/assets/5bfbc66a-1af6-438f-8087-fce7964563d5)

**Task:**
- [ ] Skapa en detaljerad sida för användaren som visar namn, efternamn, e-postadress, köphistorik och adress information.
- [ ] Skapa en lista som visar användarens köphistorik. 
- [x] Skapa en knapp som uppdaterar användarens e-postadress.
- [x] Skapa en knapp som tar bort användaren.

**Acceptanskriterier:**
- [ ] Användaren ska visas med relevant information så som namn, efternamn, köphistorik, e-postadress och adressinformation.
- [ ] Det ska gå och uppdatera användarens e-postadress i databasen.
- [ ] Det ska gå och ta bort användarens information från databasen.
- [ ] Det ska gå och se användarens order historik och produkter användaren har beställt.
