### ISSUE TITLE
Som en admin vill jag kunna ta bort en användare från sidan så att jag kan hantera och säkerställa att endast behöriga användare har tillgång till tjänsten.

### ISSUE THREAD

**Issue by HugoSpangberg** [Rika-group-7/Rika-AdminPortal-Webapp#70]
**Aktivitets Diagram:**
![image](https://github.com/user-attachments/assets/23b3e3b2-0455-4f27-ac21-806b88857303)

**Sekvens Diagram:**
![image](https://github.com/user-attachments/assets/4c58e420-6cd0-4a8e-9cb7-4833f53438d0)

**Task:**
- [x] Implementera en knapp som man kan trycka på för att ta bort en användare på profil sidan.
- [x] När man trycker på knappen så ska den ta bort hela användarens profil från databasen.
- [x] Skicka tillbaka ett meddelande om användaren har lyckats ta bort eller inte.

**Acceptanskriterier:**
- [ ] Användarens information ska försvinna från databasen. 
- [x] Korrekt meddelande ska visas om något gått rätt eller fel.

**Testkriterier:**
- [ ] Säkerställ att användare i databasen tas bort från databasen.
**Förväntat resultat:** Användaren finns inte längre i databasen.
